-- AlterTable
ALTER TABLE `Event` MODIFY `status` ENUM('DRAFT', 'PENDING_PAYMENT', 'PENDING_MODERATION', 'APPROVED', 'REJECTED', 'BANNED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `Hero` ADD COLUMN `statusReason` VARCHAR(191) NULL,
    MODIFY `status` ENUM('DRAFT', 'PENDING_PAYMENT', 'PENDING_MODERATION', 'APPROVED', 'REJECTED', 'BANNED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `Spot` ADD COLUMN `statusReason` VARCHAR(191) NULL,
    MODIFY `status` ENUM('DRAFT', 'PENDING_PAYMENT', 'PENDING_MODERATION', 'APPROVED', 'REJECTED', 'BANNED') NOT NULL DEFAULT 'DRAFT';
